version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: smeta_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smeta_db
      MYSQL_USER: smeta_user
      MYSQL_PASSWORD: smeta_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "33061:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
