services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: smeta_app
    restart: unless-stopped
    volumes:
      - ./server:/var/www/html
      - /home/denza/parser_project:/parser
    networks:
      - smeta-network

  web:
    image: nginx:alpine
    container_name: smeta_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./server:/var/www/html
      - ./docker/app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - smeta-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smeta_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: smeta_user
      PMA_PASSWORD: smeta_pass
    networks:
      - smeta-network
  db:
    image: mariadb:10.6
    container_name: smeta_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: smeta_expert
      MYSQL_USER: smeta_user
      MYSQL_PASSWORD: smeta_pass
    volumes:
      - smeta_db_data:/var/lib/mysql
      # - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smeta-network

volumes:
  smeta_db_data:

networks:
  smeta-network:
    driver: bridge

